# Generated by Django 3.0 on 2020-04-17 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Vinson管理系统', max_length=100, verbose_name='公司名称')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='公司logo')),
                ('show', models.BooleanField(default=True, verbose_name='是否显示')),
                ('box1_title', models.CharField(blank=True, max_length=20, null=True, verbose_name='首页宣传1标题')),
                ('box1_desc', models.TextField(blank=True, max_length=60, null=True, verbose_name='首页宣传1简述')),
                ('box1_url', models.CharField(blank=True, max_length=60, null=True, verbose_name='首页宣传1链接地址')),
                ('box2_title', models.CharField(blank=True, max_length=20, null=True, verbose_name='首页宣传2标题')),
                ('box2_desc', models.TextField(blank=True, max_length=60, null=True, verbose_name='首页宣传2简述')),
                ('box2_url', models.CharField(blank=True, max_length=60, null=True, verbose_name='首页宣传2链接地址')),
                ('box3_title', models.CharField(blank=True, max_length=20, null=True, verbose_name='首页宣传3标题')),
                ('box3_desc', models.TextField(blank=True, max_length=60, null=True, verbose_name='首页宣传3简述')),
                ('box3_url', models.CharField(blank=True, max_length=60, null=True, verbose_name='首页宣传3链接地址')),
                ('box4_title', models.CharField(blank=True, max_length=20, null=True, verbose_name='首页宣传4标题')),
                ('box4_desc', models.TextField(blank=True, max_length=60, null=True, verbose_name='首页宣传4简述')),
                ('box4_url', models.CharField(blank=True, max_length=60, null=True, verbose_name='首页宣传4链接地址')),
                ('company_desc', models.TextField(blank=True, null=True, verbose_name='公司简述')),
                ('footer_desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='底部栏描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '公司',
                'verbose_name_plural': '公司',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('image', models.ImageField(blank=True, null=True, upload_to='employee/', verbose_name='头像')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='职位')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '员工管理',
                'verbose_name_plural': '员工管理',
            },
        ),
    ]
