# Generated by Django 3.0 on 2020-04-17 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='box1_desc',
        ),
        migrations.RemoveField(
            model_name='company',
            name='box1_title',
        ),
        migrations.RemoveField(
            model_name='company',
            name='box1_url',
        ),
        migrations.RemoveField(
            model_name='company',
            name='box2_desc',
        ),
        migrations.RemoveField(
            model_name='company',
            name='box2_title',
        ),
        migrations.RemoveField(
            model_name='company',
            name='box2_url',
        ),
        migrations.RemoveField(
            model_name='company',
            name='box3_desc',
        ),
        migrations.RemoveField(
            model_name='company',
            name='box3_title',
        ),
        migrations.RemoveField(
            model_name='company',
            name='box3_url',
        ),
        migrations.RemoveField(
            model_name='company',
            name='box4_desc',
        ),
        migrations.RemoveField(
            model_name='company',
            name='box4_title',
        ),
        migrations.RemoveField(
            model_name='company',
            name='box4_url',
        ),
    ]
