# Generated by Django 3.0 on 2020-04-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0003_auto_20200417_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='notice_content',
            field=models.TextField(default='', verbose_name='宣传内容'),
        ),
        migrations.AddField(
            model_name='company',
            name='notice_title',
            field=models.CharField(default='', max_length=100, verbose_name='宣传标题'),
        ),
    ]
