# Generated by Django 3.0 on 2020-04-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0005_friendlylink'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address_province',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='省市区'),
        ),
        migrations.AddField(
            model_name='company',
            name='address_street',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='街道楼号'),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='联系电话'),
        ),
    ]
