# Generated by Django 3.0 on 2020-04-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0006_auto_20200420_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机')),
                ('email', models.CharField(blank=True, max_length=30, null=True, verbose_name='电子邮件')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
            ],
            options={
                'verbose_name': '在线留言',
                'verbose_name_plural': '在线留言',
            },
        ),
    ]
