# Generated by Django 3.0 on 2020-04-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0008_usermessage_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='footer_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='底部公司logo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='头部公司logo'),
        ),
    ]
