# Generated by Django 3.0 on 2020-04-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0009_auto_20200422_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='标题'),
        ),
    ]
