# Generated by Django 3.0 on 2020-04-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0010_auto_20200422_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='title',
            field=models.CharField(default='未知标题', max_length=30, verbose_name='标题'),
        ),
    ]
