# Generated by Django 3.0 on 2020-05-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companys', '0012_auto_20200422_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='姓名'),
        ),
    ]
