# Generated by Django 3.0 on 2020-04-20 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='招聘职位')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='岗位描述')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='相关要求')),
                ('show', models.BooleanField(default=True, max_length=5, verbose_name='是否显示')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '职位发布',
                'verbose_name_plural': '职位发布',
            },
        ),
    ]
