# Generated by Django 3.0 on 2020-04-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话'),
        ),
    ]
