# Generated by Django 3.0 on 2020-05-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='has_Inner',
            field=models.CharField(default=True, max_length=100, verbose_name='是否内部链接'),
        ),
    ]
