# Generated by Django 3.0 on 2020-05-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_navigation_has_inner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='has_Inner',
            field=models.BooleanField(default=True, max_length=10, verbose_name='是否内部链接'),
        ),
    ]
