# Generated by Django 3.0 on 2020-04-16 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('desc_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述1')),
                ('desc_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述2')),
                ('desc_3', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述3')),
                ('show_button', models.BooleanField(default=True, verbose_name='是否显示按钮')),
                ('index', models.IntegerField(default=1, verbose_name='显示顺序')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner/%Y/%m', verbose_name='轮播图')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
        ),
    ]
