# Generated by Django 3.0 on 2020-04-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '轮播图', 'verbose_name_plural': '轮播图'},
        ),
    ]
