# Generated by Django 3.0 on 2020-05-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200502_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='has_Inner',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='是否内部链接'),
        ),
    ]
