# Generated by Django 3.0 on 2020-05-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200502_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='has_Inner',
            field=models.BooleanField(default=True, verbose_name='是否内部链接'),
        ),
    ]
