# Generated by Django 3.0 on 2020-04-16 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_systemsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsetting',
            options={'verbose_name': '系统设置', 'verbose_name_plural': '系统设置'},
        ),
    ]
