# Generated by Django 3.0 on 2020-04-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200416_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='公司logo'),
        ),
    ]
