# Generated by Django 3.0 on 2020-05-02 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200502_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='desc_3',
        ),
    ]
