# Generated by Django 3.0 on 2020-04-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_systemsetting_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='box1_desc',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='宣传1简述'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='box1_title',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='宣传1标题'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='box2_desc',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='宣传2简述'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='box2_title',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='宣传2标题'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='box3_desc',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='宣传3简述'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='box3_title',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='宣传3标题'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='box4_desc',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='宣传4简述'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='box4_title',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='宣传4标题'),
        ),
    ]
