# Generated by Django 3.0 on 2020-04-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200416_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='box1_desc',
            field=models.TextField(blank=True, max_length=60, null=True, verbose_name='宣传1简述'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='box2_desc',
            field=models.TextField(blank=True, max_length=60, null=True, verbose_name='宣传2简述'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='box3_desc',
            field=models.TextField(blank=True, max_length=60, null=True, verbose_name='宣传3简述'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='box4_desc',
            field=models.TextField(blank=True, max_length=60, null=True, verbose_name='宣传4简述'),
        ),
    ]
