# Generated by Django 3.0 on 2020-04-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200416_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='box1_url',
            field=models.TextField(blank=True, max_length=60, null=True, verbose_name='宣传1链接地址'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='box2_url',
            field=models.TextField(blank=True, max_length=60, null=True, verbose_name='宣传2链接地址'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='box3_url',
            field=models.TextField(blank=True, max_length=60, null=True, verbose_name='宣传3链接地址'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='box4_url',
            field=models.TextField(blank=True, max_length=60, null=True, verbose_name='宣传4链接地址'),
        ),
    ]
