# Generated by Django 3.0 on 2020-04-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_circleitem_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circleitem',
            name='type',
            field=models.CharField(choices=[('big', '大'), ('small', '小')], default='大', max_length=10, verbose_name='显示类型'),
        ),
    ]
