# Generated by Django 3.0 on 2020-08-24 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('phone', models.CharField(max_length=11, verbose_name='电话')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('school', models.CharField(max_length=100, verbose_name='所报学校')),
                ('major', models.CharField(max_length=100, verbose_name='所报专业')),
                ('gender', models.IntegerField(choices=[(0, '自考'), (1, '成教'), (2, '国开')], default=0)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '报名',
                'verbose_name_plural': '报名',
            },
        ),
    ]
