# Generated by Django 3.0 on 2020-08-26 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='gender',
            new_name='type',
        ),
    ]
