# Generated by Django 3.0 on 2020-08-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20200826_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='identityCard/', verbose_name='身份证正面'),
        ),
    ]
