# Generated by Django 3.0 on 2020-08-26 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='image',
            new_name='identity_card1',
        ),
    ]
