# Generated by Django 3.0 on 2020-08-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20200826_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='graduate_photo',
            field=models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='graduate/', verbose_name='毕业证'),
        ),
        migrations.AddField(
            model_name='report',
            name='identity_card2',
            field=models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='identityCard/', verbose_name='身份证背面'),
        ),
        migrations.AlterField(
            model_name='report',
            name='identity_card1',
            field=models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='identityCard/', verbose_name='身份证正面'),
        ),
    ]
